### ISSUE TITLE
Add reusable group

### ISSUE THREAD

**Issue by mjy9088** [seui-engine/raytracing-csg-renderer#2]
Don't rely on YAML's feature.

Example:

```yml
defs:
  MyModel:
    type: intersection
    a: # ...
    b: # ...
models:
  - type: group
    transforms: # ...
    children:
      - type: ref
        ref: MyModel
```
